### PR TITLE
Feat/new jobs

### LINKED ISSUE #53: add new job (Builder)
award xp for placing blocks

### LINKED ISSUE #54: Add Monster Hunter job

### PR DESCRIPTION
**Pull request by MartinRostejnsky**
closes #53 closes #54 references #56

### CODE REVIEW

**Review by FrantisekSilhan — APPROVED** [review]
lgtm

**Review by Mapetr — APPROVED** [review]
Could be better

**Comment by MartinRostejnsky** [comment]
don't delete the branch pls :3

**Comment by MartinRostejnsky** [comment]
actually nvm

**Pull request merged**
